#!/usr/bin/env python3

from instc.compilers import compile_jvm
import sys
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("input", help="compiler input file")
parser.add_argument("-d", metavar="output_dir", help="compiler output directory", default=None)

args = parser.parse_args()

compile_jvm(args.input, args.d)
